### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by jasonlaw** [AndriousSolutions/mvc_application#1]
Do you plan to include the login features into the framework?

**Comment by Andrious** [comment]
Login features?  Are you referring to the Auth library?  I intend to supply the Auth library as a separate PUB package. The framework will be then another PUB package. Each require such distinction dependencies that separating them is more advantageous.  If or when they wish, a developer merely includes them both in their pubspec.yaml.

**Comment by jasonlaw** [comment]
What I mean is the framework can facilitate a standard login process flow, eg, silent login if has authenticated before which will route to the main home page, otherwise it will be route to a login page, by providing the placeholder (or event) for the developer to handle the actual login stuff.

User login is very common to a mobile app, so I think it would be great to be part of the application framework.
