### ISSUE TITLE
Package not working in Flutter Web (dart.io)

### ISSUE THREAD

**Issue by flokfp** [AndriousSolutions/mvc_application#10]
Due to changes in the dart.io library, it is no longer supported in flutter web. (see https://api.flutter.dev/flutter/dart-io/dart-io-library.html)

view\app.dart (https://github.com/AndriousSolutions/mvc_application/blob/master/lib/src/view/app.dart) contains 
`import 'dart:io' show Platform; `
This leads to an error when starting flutter web.

Please change the import/platform-checks to universal ones that work on all platforms.

see
https://pub.dev/packages/universal_platform
or
https://pub.dev/packages/universal_io

**Comment by Andrious** [comment]
Excellent find! 
I would hope the recent changes will now allow for starting flutter web.
Indeed,  the latest release (v. 5.3.1) has replaced 'dart:io' with the package, [universal_platform](https://pub.dev/packages/universal_platform) - a Web-safe Platform class.
You will find those changes now in the source code: [app.dart](https://github.com/AndriousSolutions/mvc_application/blob/master/lib/src/view/app.dart#L17)

As an aside, please let me know how the MVC architecture works for you on the Web platform.
I simply haven't had the opportunity to develop a Web app to any real extent.

**Comment by flokfp** [comment]
Will do, just trying the default counter app for now.

It starts in web now, thanks!
