### ISSUE TITLE
Error: No named parameter with the name 'key'.

### ISSUE THREAD

**Issue by krstevski02** [AndriousSolutions/mvc_application#11]
Has anyone encountered this issue when running?

AppData/Local/Pub/Cache/hosted/pub.dartlang.org/mvc_application-5.8.0/lib/src/view/app.dart:888:11: Error: No named parameter with the name 'key'.
          key: key,
![image](https://user-images.githubusercontent.com/6547933/93113560-a1abe080-f6b9-11ea-881e-4f191de8a9ca.png)

**Comment by Andrious** [comment]
Would you upgrade to 5.10.0 please.

I recommend you reference that package in  pubspec.yaml in the following fashion:

mvc_application: ^5.0.0

This allows for 'bug fixes' and enhancements to be imported with every 'pub upgrade.'

Cheers.

**Comment by Andrious** [comment]
Whoa!?  The latest version is not been made available to Pub!?   One moment!

**Comment by Andrious** [comment]
Version 5.10.0 has been uploaded and made available.

**Comment by krstevski02** [comment]
Great 👍
