### ISSUE TITLE
Hot reload not working

### ISSUE THREAD

**Issue by kcontech** [AndriousSolutions/mvc_application#16]
Hot reload not working with default counter example

`_AssertionError ('package:flutter/src/widgets/framework.dart': Failed assertion: line 4860 pos 7: 'state._widget == null': The createState function for AppStatefulWidget returned an old or invalid state instance: AppStatefulWidget, which is not null, violating the contract for createState.)`

**Comment by kcontech** [comment]
Update the docs. Fixed it using the simple initializer instead of factory.
`View()`
instead of `View._()`

and removing:

`factory View() => _this ??= View._();`
`static View? _this;`

**Comment by Andrious** [comment]
Excellent! 
Thanks, for catching that. 

It will be corrected and released shortly.
