### ISSUE TITLE
Examples in README.md don't work

### ISSUE THREAD

**Issue by Merdin** [AndriousSolutions/mvc_application#17]
I tried to use the examples of both the [packages (pub.dev) website](https://pub.dev/packages/mvc_application/versions) and the examples in the README.md file. I also tried the different versions.

For both the examples I get these errors:
- `Missing concrete implementation of 'AppStatefulWidget.createAppState'.`
- Also `AppMVC` seems to be deprecated.

If I implement `AppStatefulWidget.createAppState` I get the this error:
- `The name 'runApp' is defined in the libraries 'package:flutter/src/widgets/binding.dart' and 'package:mvc_application/src/conditional_export.dart (via package:mvc_application/view.dart)'.`
and a lot of other errors.

Can you please update the examples?

**Comment by Andrious** [comment]
Hello, Merdin.

Yes, I'll update the examples ASAP.
Thank you for letting me know.

For now, let's see if we can't get your examples up and running. 
Please, make the following changes:

Before:
```
import 'package:flutter/material.dart';

import 'package:mvc_application/view.dart' show AppMVC, AppState, StateMVC;

import 'package:mvc_application/controller.dart' show ControllerMVC;
```
```
class MyApp extends AppMVC {
  MyApp({Key? key}) : super(key: key);

  @override
  AppState createState() => View();
}
```

After:
```
import 'package:mvc_application/view.dart';

import 'package:mvc_application/controller.dart';
```
```
void main() => runApp(MyApp());

class MyApp extends AppStatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  AppState createAppState() => View();
}
```
Note, the function, createState(), is changed to createAppState().

As for the other errors you appear to be encountering, how exactly are you 'implementing AppStatefulWidget.createAppState?'



I don't have the changes you're running in front of me, so I can only guess you're importing one of the two core packages.
You could hide 'runApp' found in the Flutter framework. 

```
import 'package:flutter/material.dart' hide runApp;

import 'package:flutter/cupertino.dart' hide runApp;

import 'package:mvc_application/view.dart';

import 'package:mvc_application/controller.dart';
```
Even better, don't import them at all. You don't have to explicitly import them when using this package:
```
import 'package:mvc_application/view.dart';

import 'package:mvc_application/controller.dart';
```

**Comment by Merdin** [comment]
Hi @Andrious thank you for the update. I will confirm somewhere next week if the examples work with your suggestions.

**Comment by Andrious** [comment]
Confirmed, no.
