### ISSUE TITLE
Version conflicts with Flutter 3.x

### ISSUE THREAD

**Issue by zodako** [AndriousSolutions/mvc_application#18]
Hey there,

I am using mvc_application 8.12.0. I did an update for my app to Flutter 3. After solving some issues, I can not resolve these last three errors, mostly because I think those are dependencies in mvc_application. Do someone know any solution?

~/flutter/.pub-cache/hosted/pub.dartlang.org/l10n_translator-3.0.1/lib/src/l10n.dart:382:42: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('~/flutter/packages/flutter/lib/src/widgets/binding.dart').
    final systemLocales = WidgetsBinding.instance!.window.locales;
                                         ^
~/flutter/.pub-cache/hosted/pub.dartlang.org/mvc_application-8.12.0/lib/src/view/app_navigator.dart:405:34: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('~/flutter/packages/flutter/lib/src/widgets/binding.dart').
    String path = WidgetsBinding.instance!.window.defaultRouteName;
                                 ^
~/flutter/.pub-cache/hosted/pub.dartlang.org/mvc_application-8.12.0/lib/src/view/app.dart:188:34: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('~/flutter/packages/flutter/lib/src/widgets/binding.dart').
      _window ??= WidgetsBinding.instance!.window;

Flutter Doctor (essential part)
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19043.1706], locale de-DE)

Thanks for help me! :)

**Comment by Andrious** [comment]
Hello there!

It would seem Flutter has changed some things allowing the 'null operator' (!) to no longer be necessary.
Allow me to look into it this morning. 

Note, they are not errors, I believe, but Warnings. With that, your app should still be able to run...only with warnings.
Regardless, I will look into these Warnings.

Greg

**Comment by zodako** [comment]
Hello Greg,

of course you are right, it is only a warning and not an error, the app builds and starts perfectly :)

Thanks for looking into it!

Bernhard

**Comment by Andrious** [comment]
Latest update have addressed the warning messages.

**Comment by zodako** [comment]
Thanks a lot! :)
