### ISSUE TITLE
Will AppController.init block home page loading?

### ISSUE THREAD

**Issue by jasonlaw** [AndriousSolutions/mvc_application#3]
If I have a long process in the AppController.init (async call), will the homepage only be loaded after the init completed?
What I am trying to do is in AppController.init will have login authentication checking, if success then continue with normal homepage loading, otherwise, will reassign the home route to a login page. Any advise/suggestion for this?

**Comment by Andrious** [comment]
Here is a working app where I 'login' in using the AppController.init(). Note, the  'await' used for signIn().
However, you're not talking about logging into Google. You're talking about logging into your own system with its own list of members. Is that right? Unfortunately, my mind is elsewhere, today. Too busy with a client. 

![image](https://user-images.githubusercontent.com/32497443/53970399-9e996280-40c8-11e9-920a-2ea94e9257c4.png)

**Comment by jasonlaw** [comment]
You are right, I am using own authentication system, not google signin.

Some side questions:
1. What would happen if we return false from the init() ?
2. I see you have a static variable con for easy access, can't we just access the same controller with the syntax: WorkingMemoryApp().someInstanceMethodOrVariable ? I would like to follow the best practice if there is any.

**Comment by Andrious** [comment]
Hi Jason,

An 'standalone' authentication system would require a database implementation and maintenance, and I'm not prepared to offer such a system in the framework at this time.

If the init() returns false, the home: Widget will still execute because snapshot.hasData is still set to true (i.e. snapshot.data != null). However, in the framework, there will be an static property, App.isInit, set to false. The idea being the 'home' widget could check the value of App.isInit and response accordingly.

As for the static variable, con, indeed you could instead use the syntax,
 WorkingMemoryApp().someInstanceMethodOrVariable.


![init](https://user-images.githubusercontent.com/32497443/54004795-ec43b880-4124-11e9-931b-4e80debb2fad.png)

**Comment by jasonlaw** [comment]
clear now, thank you very much!

**Comment by jasonlaw** [comment]
Hi,
I have a problem with the LoadingScreen here, can you please help?
I have a LandingPage which is set to home in the AppView.
In the LandingPage, I will do the silentLogin, if success will navigate to actual HomePage, otherwise LoginPage. While waiting for the login completion, the page will be showing a nice logo with some animation.

Here is part of the code:
class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    CommunityAppCon.current.silentLogin().then((success) {
      if (success) {
     //   Navigator.pushReplacementNamed(context, HomePage.tag);
      } else {
    //    Navigator.pushReplacementNamed(context, LoginPage.tag);
      }
    });
    return Scaffold(
      backgroundColor: Colors.white,
      body: _buildWidget(context),
    );
  }

The problem is, there will be always a empty white page title with "Loading" (I guess that is your LoadingScreen) before my LandingPage, and that is very annoying.

May I know how should I fix this?

Thanks in advance.

**Comment by jasonlaw** [comment]
Hi,
I have tried different approach, by doing the silentLogin in AppController.Init, and having a override function for initialRoute.

 @override
  String onInitialRoute() =>
      CommunityAppCon.current.isLogin ? HomePage.tag : LoginPage.tag;

This works, at least it can be routed to either Home or Login page accordingly, however, there are still some problems:
1. Since home argument is mandatory to the AppController, I am not sure what to set into it, hence I set to HomePage.
2. After routing to the initialRoute, the app can be navigate back to the previous page, which is home. This is not right since it could be routing from LoginPage to HomePage. Ideal way would be ignoring the home, or set the InitialRoute as home.
3. The LoadingScreen can't be customized, I would prefer to show my nice logo with animation.

Please help.

Thanks in advance.

**Comment by jasonlaw** [comment]
Hi,
I have fixed issue 1 & 2, by setting the home to a LandingPage, which will return either HomePage or LoginPage based on login flag.

However, I am not able to customize the LoadingPage. I will try to modify your code locally, please let me know if I can contribute to your code.

Thanks in advance.

**Comment by Andrious** [comment]
Indeed, Jason.  You can contribute to the code.

By the way, would you have your project on Github or Bitbucket?
I would like to clone what you have and get a better idea of what you're trying to do.

I could then better understand how I can help and how the framework could be 'adjusted' to be more adaptive. A framework should be adaptive--change its functionality to fit the particular developers need when appropriate.

Please, contact me directly by email:     support  'at'  andrioussolutions.com

Greg.
