### ISSUE TITLE
Problems with Flutter Desktop and MVC_APLICATION

### ISSUE THREAD

**Issue by tenroberto2011** [AndriousSolutions/mvc_application#8]
Gentlemen, when installing and configuring according to the video of friend Jacob on Youtube, I was able to use FD in the examples, but in a particular project where I use mvc_application, he runs FD and this information comes out on screen:
"MissingPluginException (No implementation found for method getApplicationDocumentsDirectory on channel plugin flutter.io/path_provider)"

**Comment by tenroberto2011** [comment]
![Captura de Tela 2019-10-08 às 11 01 36](https://user-images.githubusercontent.com/8239972/66435379-129f3e80-e9fb-11e9-89ff-4a6edc4bfcea.jpg)

**Comment by tenroberto2011** [comment]
"MissingPluginException (No implementation found for method getApplicationDocumentsDirectory on channel plugin flutter.io/path_provider)"

**Comment by Andrious** [comment]
From the screenshot, I see you're in your IDE.  From the query of the error message, a 'hot reload' may be the issue:  
["MissingPluginException (No implementation found for method getApplicationDocumentsDirectory on channel plugin flutter.io/path_provider)"](https://www.google.com/search?q=%22%22MissingPluginException+(No+implementation+found+for+method+getApplicationDocumentsDirectory+on+channel+plugin+flutter.io%2Fpath_provider)%22%22&oq=%22%22MissingPluginException+(No+implementation+found+for+method+getApplicationDocumentsDirectory+on+channel+plugin+flutter.io%2Fpath_provider)%22%22&aqs=chrome..69i57.7811j0j7&sourceid=chrome&ie=UTF-8)

**Comment by tenroberto2011** [comment]
An important note, when running on an iOS or Android simulator, the code works, but not on Flutter Desktop.
It will present the screen above ...

**Comment by Andrious** [comment]
Admittedly, MVC_Application was designed for mobile apps and not desktop applications. And so, yes, I would see it working in the iOS and Android mobile app simulators, but not the Flutter Desktop as of yet.

As it is, Flutter Desktop is still under development, it hasn't yet a stable plugin system:
["Writing plugins is supported on all platforms, however there are currently very few plugins that actually have desktop support."](https://github.com/flutter/flutter/wiki/Desktop-shells#plugins)

You will find a short list of plugins that can be used, but the path_provider plugin is currently not one of them: [Desktop Plugins](https://github.com/google/flutter-desktop-embedding/tree/master/plugins)

I appreciate your intent to use MVC_Application in a Flutter Desktop app, but neither is ready for the other at this time. In a few months, this may change.

Cheers.

Greg

**Comment by tenroberto2011** [comment]
Thank you very much !!!
Excellent explanation !!!
